# Generated by Django 5.1.1 on 2024-09-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postgres://default:EtBmPUi5Ys3A@ep-still-wave-a4todl50-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require'),
        ),
    ]
